# Details
title:       François Bruneau
description: Un blog cinéma et photo
url:         https://www.francoisbruneau.com

#Author
author:
  name:      'François Bruneau'
  url:       https://about.me/francois.bruneau
  email:     contact@francoisbruneau.com

paginate:    3
paginate_path: "/:num/"

# Permalinks
permalink:   /:categories/:title/

# Build settings
# destination: dest
# source:      src # Removed because Github Pages does not allow different source directory
markdown:    kramdown
highlighter: rouge

# Gems
gems:
  - jekyll-paginate
  - jekyll-feed

# Plugins unavailable on Github Pages
# TODO: Replace by http://www.minddust.com/post/tags-and-categories-on-github-pages/
#  - jekyll-tagging
#  - jekyll-tagging-related_posts
